spring:
    thymeleaf:
        cache: false
    datasource:
        url: jdbc:postgresql://localhost:5432/futmemdb
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
    session:
        store-type: redis
    redis:
        host: localhost
        port: 6379
